### ISSUE TITLE
How can I deploy assayM on my system

### ISSUE THREAD

**Issue by Rohit-Satyam** [raeece/assayM#1]
Dear Developer!!

I was trying to run your app on my laptop but I get the following error:

![image](https://user-images.githubusercontent.com/55479480/156805555-5c03d783-7bf4-48a0-915c-6bbd43f0cee2.png)
 Can you point me where can I get the `vmeta` table?

**Comment by raeece** [comment]
The R code is deprecated.
The [live application](https://grafnet.kaust.edu.sa/assayM)  is based on the python code.
Please use the python code in https://github.com/raeece/assayM/tree/main/python
You probably need GISAID account and endpoint to build the latest database of sequences.
